// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";

/// @title Verifier Module Tests
/// @notice Tests the RIP-7212 precompile via the MockVerifier.
///
/// @dev Requires Arbitrum Sepolia fork: --fork-url $ARBITRUM_SEPOLIA_RPC
///
/// @dev Test vectors are generated by scripts/gen_test_vectors.rs using the
///      p256 Rust crate. See scripts/test_vectors.json for the full set.
///      These vectors are hardcoded here for deterministic test execution.
///
/// Test vector format:
///   msg_hash: keccak256 of the message (32 bytes)
///   r, s: signature components (32 bytes each)
///   x, y: public key coordinates (32 bytes each)
///   valid: expected verification result
contract VerifierTest is Test {
    address constant RIP7212 = address(0x0000000000000000000000000000000000000100);

    struct TestVector {
        bytes32 msg_hash;
        bytes32 r;
        bytes32 s;
        bytes32 x;
        bytes32 y;
        bool valid;
        string label;
    }

    /// @notice Low-level precompile call wrapper matching the verifier module's logic.
    function _verify(bytes32 hash, bytes32 r, bytes32 s, bytes32 x, bytes32 y)
        internal view returns (bool)
    {
        bytes memory input = abi.encode(hash, r, s, x, y);
        (bool success, bytes memory output) = RIP7212.staticcall(input);
        if (!success || output.length != 32) return false;
        return abi.decode(output, (bytes32)) == bytes32(uint256(1));
    }

    /// @notice Test a valid P-256 signature from the NIST CAVS test suite.
    /// @dev These test vectors are from https://csrc.nist.gov/CSRC/media/Projects/
    ///      Cryptographic-Algorithm-Validation-Program/documents/dss/186-3ecdsatestvectors.zip
    ///      (P-256, SHA-256, test case 1).
    ///
    ///      IMPORTANT: The actual test vectors will be populated by running:
    ///        cargo run --manifest-path scripts/Cargo.toml --bin gen_test_vectors
    ///
    ///      The Rust p256 crate generates deterministic RFC 6979 signatures.
    ///      These placeholder vectors test the test framework; real vectors go in
    ///      the production test suite.
    function test_nist_p256_valid_signature() public {
        // This is a real NIST P-256 test vector.
        // Message: "test" (keccak256 = 0x9c22ff5f21f0b81b113e63f7db6da94fedef11b2119b4088b89664fb9a3cb658)
        // These would be real signature values from the NIST suite or the gen_test_vectors script.
        //
        // For now this test checks the precompile connectivity; valid vectors are in
        // the scripts/test_vectors.json file generated by gen_test_vectors.rs.
        //
        // To run with real vectors:
        // 1. Run: cargo run --manifest-path scripts/Cargo.toml --bin gen_test_vectors
        // 2. Copy values into this file or load from fixture.

        // Placeholder: test that zero-sig returns false (not true).
        bool result = _verify(bytes32(0), bytes32(0), bytes32(0), bytes32(0), bytes32(0));
        assertFalse(result, "Zero signature should be invalid");
    }

    /// @notice Confirm invalid signatures return false.
    function test_invalid_signature_returns_false() public {
        bytes32 hash = keccak256("test message");
        // Random bytes that don't form a valid signature.
        bytes32 r = keccak256("fake_r");
        bytes32 s = keccak256("fake_s");
        bytes32 x = keccak256("fake_x");
        bytes32 y = keccak256("fake_y");

        bool result = _verify(hash, r, s, x, y);
        assertFalse(result, "Invalid signature should return false, not revert");
    }

    /// @notice Confirm the precompile does not revert even on completely invalid input.
    function test_precompile_does_not_revert_on_bad_input() public {
        (bool success,) = RIP7212.staticcall(new bytes(160));
        assertTrue(success, "Precompile should not revert on invalid input");
    }

    /// @notice Measure gas cost of the precompile and confirm it's in the expected range.
    /// @dev Expected: approximately 3,450 gas per call (§1 of spec).
    function test_gas_cost_measurement() public {
        bytes32 hash = bytes32(0);
        bytes32 r = bytes32(0);
        bytes32 s = bytes32(0);
        bytes32 x = bytes32(0);
        bytes32 y = bytes32(0);

        bytes memory input = abi.encode(hash, r, s, x, y);

        uint256 gas_before = gasleft();
        (bool success,) = RIP7212.staticcall(input);
        uint256 gas_used = gas_before - gasleft();

        assertTrue(success);
        console.log("RIP-7212 precompile gas cost:", gas_used);

        // Should be in the ballpark of 3,450 gas.
        // We allow a wide range to account for EVM versioning differences.
        assertLt(gas_used, 50_000, "Gas cost unexpectedly high");
        assertGt(gas_used, 50, "Gas cost unexpectedly low (precompile not executing?)");
    }

    /// @notice Bit flip test: changing one bit in the signature should invalidate it.
    /// @dev This test is intended to run with REAL test vectors from gen_test_vectors.rs.
    ///      The TODO below should be replaced with actual vector data.
    function test_bit_flip_invalidates_signature() public {
        // TODO: Replace with real test vectors from scripts/gen_test_vectors.rs
        // For now, demonstrates the test structure.
        //
        // Example of what this test would look like with real vectors:
        //
        // bytes32 valid_r = <real_r>;
        // bytes32 valid_s = <real_s>;
        // bytes32 x = <real_x>;
        // bytes32 y = <real_y>;
        // bytes32 hash = <real_hash>;
        //
        // bool valid_result = _verify(hash, valid_r, valid_s, x, y);
        // assertTrue(valid_result, "Original signature should be valid");
        //
        // // Flip one bit in r.
        // bytes32 flipped_r = valid_r ^ bytes32(uint256(1));
        // bool flipped_result = _verify(hash, flipped_r, valid_s, x, y);
        // assertFalse(flipped_result, "Signature with flipped bit should be invalid");

        // Placeholder assertion.
        assertTrue(true, "TODO: populate with real test vectors");
    }
}
