/**
 * Audit-trail bookkeeping for the Matrix-subsystem credentials generated by
 * scripts/generate-matrix-secrets.ts (implementation-plan.md Steps 7/7b/7c).
 *
 * These credentials are consumed by the `synapse` container / Python
 * policy-module process, not by wallet-service itself — so the normal
 * SecretsService.decryptSecret-at-use-time flow (server/utils/secrets.ts,
 * used by e.g. src/routes/accounts-create.ts) doesn't apply here. What this
 * module provides instead is a `matrix_credentials` Postgres row per
 * credential, encrypted the same way (SecretsService.encryptSecret), kept
 * purely for audit/recovery/rotation bookkeeping: proof of what was
 * generated and when, and a way to recover the value if the on-disk copy
 * (`key_file_path`) is ever lost, without introducing a second,
 * undocumented key-management scheme for these three credentials.
 */

import type { Pool } from 'pg';
import type { SecretsService } from './secrets/index.js';

export interface MatrixCredentialRecord {
  credentialName: string;
  keyFilePath: string;
  description: string;
  createdAt: Date;
  rotatedAt: Date | null;
}

export interface RecordMatrixCredentialParams {
  credentialName: string;
  plaintext: Buffer;
  keyFilePath: string;
  description: string;
}

/**
 * Encrypts `plaintext` via the existing secrets abstraction and upserts the
 * resulting ciphertext/DEK as an audit row. Re-running this for the same
 * `credentialName` (rotation) overwrites the previous row and stamps
 * `rotated_at` — it does not keep prior ciphertexts, since the source of
 * truth for "what's live right now" is the file at `keyFilePath`, not this
 * table.
 */
export async function recordMatrixCredential(
  pool: Pool,
  secretsService: SecretsService,
  params: RecordMatrixCredentialParams
): Promise<void> {
  const { ciphertext, dekEnc } = await secretsService.encryptSecret(params.plaintext);
  await pool.query(
    `INSERT INTO matrix_credentials (credential_name, ciphertext, dek_enc, key_file_path, description)
     VALUES ($1, $2, $3, $4, $5)
     ON CONFLICT (credential_name) DO UPDATE SET
       ciphertext = EXCLUDED.ciphertext,
       dek_enc = EXCLUDED.dek_enc,
       key_file_path = EXCLUDED.key_file_path,
       description = EXCLUDED.description,
       rotated_at = now()`,
    [params.credentialName, ciphertext, dekEnc, params.keyFilePath, params.description]
  );
}

export async function listMatrixCredentials(pool: Pool): Promise<MatrixCredentialRecord[]> {
  const { rows } = await pool.query<{
    credential_name: string;
    key_file_path: string;
    description: string;
    created_at: Date;
    rotated_at: Date | null;
  }>(
    `SELECT credential_name, key_file_path, description, created_at, rotated_at
     FROM matrix_credentials
     ORDER BY credential_name`
  );
  return rows.map((r) => ({
    credentialName: r.credential_name,
    keyFilePath: r.key_file_path,
    description: r.description,
    createdAt: r.created_at,
    rotatedAt: r.rotated_at,
  }));
}

/** Recovery path: reconstructs a credential's raw bytes from its audit record, e.g. if `key_file_path` was lost. */
export async function decryptMatrixCredential(
  pool: Pool,
  secretsService: SecretsService,
  credentialName: string
): Promise<Buffer | null> {
  const { rows } = await pool.query<{ ciphertext: string; dek_enc: string }>(
    `SELECT ciphertext, dek_enc FROM matrix_credentials WHERE credential_name = $1`,
    [credentialName]
  );
  const row = rows[0];
  if (!row) return null;
  return secretsService.decryptSecret(row.ciphertext, row.dek_enc);
}
