export { UuidConnection } from "./durable-object";

// Phase 1.2 spike worker entry.
//
// This is a hand-written Worker entry, NOT generated by Nitro's build
// pipeline — see README.md "Why this is a separate worker" for why: Nitro's
// shipped `cloudflare-durable` preset (nitropack@2.11+) hardcodes a single
// fixed Durable Object instance name ("server") with no config surface to
// override it per-request in this version, so it cannot address one DO per
// UUID out of the box. This worker resolves a distinct DO instance per UUID
// itself via `idFromName(uuid)`, then talks to the Hibernation API
// (`acceptWebSocket`/`getWebSockets`) directly inside that DO class — see
// durable-object.ts.

export interface Env {
  UUID_CONNECTION: DurableObjectNamespace;
}

function extractUuid(pathname: string, prefix: string): string | null {
  if (!pathname.startsWith(prefix)) return null;
  const rest = pathname.slice(prefix.length);
  return rest.length > 0 ? rest : null;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    // GET /ws/{uuid} — device opens the delivery WebSocket for this UUID.
    const wsUuid = extractUuid(url.pathname, "/ws/");
    if (wsUuid && request.headers.get("upgrade") === "websocket") {
      const id = env.UUID_CONNECTION.idFromName(wsUuid);
      const stub = env.UUID_CONNECTION.get(id);
      const doUrl = new URL(request.url);
      doUrl.searchParams.set("uuid", wsUuid);
      return stub.fetch(new Request(doUrl, request));
    }

    // POST /deliver/{uuid} — simulates the relay's real /deliver/{uuid}
    // routing a message to whichever DO instance (if any) holds that
    // UUID's open WebSocket. Routes to the SAME DO instance as the /ws/
    // call above because idFromName(uuid) is deterministic.
    const deliverUuid = extractUuid(url.pathname, "/deliver/");
    if (deliverUuid && request.method === "POST") {
      const id = env.UUID_CONNECTION.idFromName(deliverUuid);
      const stub = env.UUID_CONNECTION.get(id);
      const deliverUrl = new URL(request.url);
      deliverUrl.pathname = "/deliver";
      return stub.fetch(new Request(deliverUrl, request));
    }

    // GET /status/{uuid} — spike-only introspection endpoint.
    const statusUuid = extractUuid(url.pathname, "/status/");
    if (statusUuid) {
      const id = env.UUID_CONNECTION.idFromName(statusUuid);
      const stub = env.UUID_CONNECTION.get(id);
      const statusUrl = new URL(request.url);
      statusUrl.pathname = "/status";
      return stub.fetch(new Request(statusUrl, request));
    }

    if (url.pathname === "/health") {
      return Response.json({ status: "ok" });
    }

    return new Response("not found", { status: 404 });
  },
};
