import { describe, it, expect, afterEach } from 'vitest';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { readAppServiceAsToken, readAppServiceHsToken } from '../src/matrix/appservice-tokens.js';

// Exercises the path-override escape hatch (real path is
// matrix/secrets/appservice-{as,hs}-token.txt, generated by
// scripts/generate-matrix-secrets.ts — not present in a bare checkout) by
// pointing at a fixture file instead.
describe('appservice token readers (Step 15a/15b/15c)', () => {
  let dir: string;

  afterEach(() => {
    if (dir) rmSync(dir, { recursive: true, force: true });
  });

  it('reads and trims the as_token file', () => {
    dir = mkdtempSync(path.join(tmpdir(), 'matrix-secrets-'));
    const filePath = path.join(dir, 'appservice-as-token.txt');
    writeFileSync(filePath, 'deadbeef\n');
    expect(readAppServiceAsToken(filePath)).toBe('deadbeef');
  });

  it('reads and trims the hs_token file', () => {
    dir = mkdtempSync(path.join(tmpdir(), 'matrix-secrets-'));
    const filePath = path.join(dir, 'appservice-hs-token.txt');
    writeFileSync(filePath, 'cafebabe\n');
    expect(readAppServiceHsToken(filePath)).toBe('cafebabe');
  });
});
