// @vitest-environment jsdom
import 'fake-indexeddb/auto';
import { webcrypto } from 'crypto';
import { describe, it, expect, vi } from 'vitest';
import {
  createCardVerifier,
  requestSubCard,
  mlDsa44GenerateKeypair,
  mlDsa44Sign,
  mlDsa44Verify,
  canonicalize,
  keccak256,
} from '@membership-card-protocol/app-sdk';
import { base64UrlToBytes } from '@membership-card-protocol/app-sdk';
import type { IpfsProvider, RpcProvider, WalletAppCardIdentity, SignedSubCardDocument } from '@membership-card-protocol/app-sdk';
import { handleSubCardRequest } from '../../src/subcards/handleSubCardRequest.js';
import { assembleSubCardConsent } from '../../src/subcards/consent.js';
import { countersignSubCardRequest } from '../../src/subcards/countersign.js';
import { WebCryptoSecureKeyProvider } from '@membership-card-protocol/sdk-providers-web';

/**
 * Cross-platform scenario test (Step 3.2c): the full sub-card authorization
 * pipeline — `handleSubCardRequest` → `assembleSubCardConsent` →
 * `countersignSubCardRequest` — using a *real* `WebCryptoSecureKeyProvider`
 * from `sdk-providers-web` for the requesting app's sub-card key (the
 * `SecureKeyProvider`-backed half of this flow, per `app_sdk.md §7.1`'s
 * `requestSubCard`). `crypto.subtle` (WebCrypto AES-GCM key wrapping) and a
 * real `indexedDB` (via `fake-indexeddb`, since jsdom ships neither) are
 * both exercised for real here — `WebCryptoSecureKeyProvider.generateKey`/
 * `.sign` round-trip through actual IndexedDB storage and actual
 * non-extractable `CryptoKey` wrapping, not a fake in-memory Map.
 *
 * The holder's own master key is *not* routed through `SecureKeyProvider`
 * in this package's design — `wallet_sdk.md §10` is explicit that master-key
 * custody has no `SecureKeyProvider` abstraction (`countersignSubCardRequest`
 * takes a direct `masterSecretKey: Uint8Array`, mirroring
 * `subCardDeregistration.ts`'s no-signer-substitution pattern) — so this
 * scenario keeps the master key as a raw in-memory keypair, matching how
 * every other wallet-sdk call site (and its own unit tests) already does.
 */

if (!globalThis.crypto.subtle) {
  Object.defineProperty(globalThis.crypto, 'subtle', {
    value: webcrypto.subtle,
    writable: false,
    configurable: false,
  });
}

const GOVERNANCE_APP_CERT_ROOT = 'ff'.repeat(32);

const fakeIpfs: IpfsProvider = {
  fetch: async () => {
    throw new Error('not used — fetchAnnotations is false');
  },
};

function makeFakeAppCard(): WalletAppCardIdentity {
  const keypair = mlDsa44GenerateKeypair();
  return {
    cardPointer: keccak256(keypair.publicKey),
    publicKey: keypair.publicKey,
    sign: (message: Uint8Array) => mlDsa44Sign(keypair.secretKey, message),
  };
}

function makeHappyPathRpc(appCardAddress: string): RpcProvider {
  return {
    getCardEntry: async (address) =>
      address === appCardAddress
        ? { log_head_cid: 'cid', policy_address: 'policy', last_press_address: 'press', forward_to: null, exists: true }
        : null,
    isPolicyAuthorizer: async (address) => address === appCardAddress,
    getPressAuthorization: async () => null,
    getSubCardEntry: async () => null,
    getCardEventLog: async () => [],
    getEasAnnotations: async () => [],
  };
}

describe('Sub-card authorization pipeline end-to-end (real WebCryptoSecureKeyProvider, Step 3.2c)', () => {
  it('validates, consents, and countersigns a sub-card request whose app-side key was generated and signed by a real WebCryptoSecureKeyProvider', async () => {
    const secureKeyProvider = new WebCryptoSecureKeyProvider();
    const appCard = makeFakeAppCard();
    const holder = mlDsa44GenerateKeypair();

    // Step 1 (App SDK, requester side): the requesting app's sub-card key
    // is generated by the real WebCryptoSecureKeyProvider — a genuine
    // non-extractable CryptoKey wraps the ML-DSA-44 secret key, persisted
    // via real IndexedDB (fake-indexeddb), not an in-memory Map.
    const { document, subCardPublicKey } = await requestSubCard({
      secureKeyProvider,
      subCardKeyId: 'scenario-app-sub-card-key',
      appCard,
      holderPrimaryCard: keccak256(holder.publicKey),
      holderPrimaryCardPubkey: holder.publicKey,
      capabilities: ['auth_response'],
      attestationLevel: 'T1',
    });

    // Confirm the key is really retrievable back out of the real provider
    // (round-tripped through IndexedDB + WebCrypto unwrap), not just
    // returned once from generateKey. Compared as plain arrays since the
    // structured-clone round trip through fake-indexeddb can return a
    // Uint8Array view with different buffer/byteOffset metadata despite
    // identical byte values.
    const roundTrippedPubkey = await secureKeyProvider.getPublicKey('scenario-app-sub-card-key');
    expect(roundTrippedPubkey).toBeDefined();
    expect(Array.from(roundTrippedPubkey!)).toEqual(Array.from(subCardPublicKey));

    const appCardAddress = keccak256(appCard.publicKey);
    const cardVerifier = createCardVerifier({
      rpc: makeHappyPathRpc(appCardAddress),
      ipfs: fakeIpfs,
      appCertificationRoot: GOVERNANCE_APP_CERT_ROOT,
      trustedRoots: [GOVERNANCE_APP_CERT_ROOT, appCardAddress],
    });

    // Step 2 (wallet-side): validate the app-signed request.
    const validated = await handleSubCardRequest({ cardVerifier, request: document });
    expect(validated.valid).toBe(true);
    if (!validated.valid) throw new Error('unreachable');

    // Step 3: assemble consent (self-authorized in this scenario, same as
    // any granter approving in full).
    const consentData = assembleSubCardConsent({
      validated,
      appIdentity: { name: 'Scenario App' },
      walletGrantableCapabilities: ['auth_response'],
    });

    // Step 4: countersign with the holder's master key (never routed
    // through SecureKeyProvider — see this file's doc comment).
    const registerSubCard = vi.fn(async (_doc: SignedSubCardDocument) => ({ registered: true }));
    const outcome = await countersignSubCardRequest({
      consentData,
      decision: { approved: true, approvedCapabilities: consentData.requestedCapabilities },
      masterSecretKey: holder.secretKey,
      registerSubCard,
    });

    expect(outcome.countersigned).toBe(true);
    if (!outcome.countersigned) throw new Error('unreachable');
    expect(outcome.registered).toBe(true);
    expect(registerSubCard).toHaveBeenCalledWith(outcome.document);

    // Verify both signatures on the finished document: app_signature
    // verifies against the sub-card key the real WebCryptoSecureKeyProvider
    // generated (via appCard.sign, which uses the app's own governance key
    // — not the sub-card key itself, matching requestSubCard's actual
    // signing model), and holder_signature verifies against the master key.
    const doc = outcome.document;
    const { app_signature, holder_signature, ...withoutSignatures } = doc;
    expect(mlDsa44Verify(appCard.publicKey, canonicalize(withoutSignatures), base64UrlToBytes(app_signature))).toBe(
      true
    );
    const withAppSig = { ...withoutSignatures, app_signature };
    expect(mlDsa44Verify(holder.publicKey, canonicalize(withAppSig), base64UrlToBytes(holder_signature))).toBe(true);

    // Confirm the sub-card's own secret key genuinely never left the real
    // SecureKeyProvider: sign an arbitrary message through the provider
    // and verify it against the public key already confirmed above,
    // rather than ever reading a raw secret key out of the provider.
    const testMessage = new TextEncoder().encode('scenario-test-message');
    const signature = await secureKeyProvider.sign('scenario-app-sub-card-key', testMessage);
    expect(mlDsa44Verify(subCardPublicKey, testMessage, signature)).toBe(true);
  });
});
